name: wchatalwzeerpro
description: "A new Flutter project for Al-Wazir Chat."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
      nearby_connections: ^4.3.0
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  file_picker: ^8.0.0
  image_picker: ^1.0.7
  video_player: ^2.8.2
  sqflite: ^2.4.4
  shared_preferences: ^2.5.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
